import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const packageJSON = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
  dependencies?: Record<string, string>;
};
const astroConfig = readFileSync(join(root, "astro.config.mjs"), "utf8");
const baseLayout = readFileSync(join(root, "src/layouts/BaseLayout.astro"), "utf8");
const assetCard = readFileSync(join(root, "src/components/catalog/AssetCard.astro"), "utf8");
const contentPage = readFileSync(join(root, "src/pages/content/[id].astro"), "utf8");
const ruContentPage = readFileSync(join(root, "src/pages/ru/content/[id].astro"), "utf8");
const apiReferencePage = readFileSync(join(root, "src/pages/api-reference.astro"), "utf8");
const ruApiReferencePage = readFileSync(join(root, "src/pages/ru/api-reference.astro"), "utf8");

assert.ok(packageJSON.dependencies?.["@astrojs/sitemap"], "@astrojs/sitemap dependency is required");
assert.match(astroConfig, /from '@astrojs\/sitemap'/);
assert.match(astroConfig, /sitemap\(/);
assert.match(astroConfig, /customSitemaps/);
assert.match(astroConfig, /trailingSlash:\s*['"]never['"]/);
assert.match(astroConfig, /customPages/);
assert.match(astroConfig, /addDefaultSitemapAlternate/);
assert.match(astroConfig, /lang:\s*['"]x-default['"]/);
assert.match(astroConfig, /\/catalog\/worlds/);
assert.match(astroConfig, /\/ru\/catalog\/prefabs/);
assert.match(astroConfig, /['"]\/login['"]/);
assert.match(astroConfig, /['"]\/404['"]/);
assert.match(astroConfig, /content-sitemap\.xml/);
assert.ok(existsSync(join(root, "src/pages/robots.txt.ts")), "robots.txt Astro endpoint is required");
assert.ok(existsSync(join(root, "src/pages/content-sitemap.xml.ts")), "runtime content sitemap endpoint is required");
assert.match(baseLayout, /rel="sitemap"/);
assert.ok(existsSync(join(root, "public/OG-Image.png")), "Open Graph image should be served from public/");
assert.match(baseLayout, /robots\?:\s*string/);
assert.match(baseLayout, /alternatePaths\?:/);
assert.match(baseLayout, /jsonLd\?:/);
assert.match(baseLayout, /socialImage\?:/);
assert.match(baseLayout, /<meta name="robots" content=\{robots\} \/>/);
assert.match(baseLayout, /rel="alternate"/);
assert.match(baseLayout, /application\/ld\+json/);
assert.match(baseLayout, /const defaultSocialImage = new URL\("\/OG-Image\.png", site\);/);
assert.match(baseLayout, /<meta property="og:image" content=\{resolvedSocialImage\.href\} \/>/);
assert.match(baseLayout, /<meta property="og:image:secure_url" content=\{resolvedSocialImage\.href\} \/>/);
assert.match(baseLayout, /<meta property="og:image:type" content=\{resolvedSocialImage\.type\} \/>/);
assert.match(baseLayout, /content=\{String\(resolvedSocialImage\.width\)\}/);
assert.match(baseLayout, /content=\{String\(resolvedSocialImage\.height\)\}/);
assert.match(baseLayout, /<meta property="og:image:alt" content=\{resolvedSocialImage\.alt\} \/>/);
assert.match(baseLayout, /<meta name="twitter:image" content=\{resolvedSocialImage\.href\} \/>/);
assert.match(baseLayout, /<meta name="twitter:image:alt" content=\{resolvedSocialImage\.alt\} \/>/);
assert.match(assetCard, /buildContentPath/);
assert.doesNotMatch(assetCard, /`\/content\/\$\{item\.id\}`/);
assert.match(contentPage, /extractContentIDFromPathParam/);
assert.match(contentPage, /Astro\.redirect\(canonicalPath,\s*301\)/);
assert.match(contentPage, /contentMetaDescription/);
assert.match(contentPage, /contentJsonLd/);
assert.match(ruContentPage, /extractContentIDFromPathParam/);
assert.match(ruContentPage, /Astro\.redirect\(canonicalPath,\s*301\)/);
for (const [label, source] of [["en", apiReferencePage], ["ru", ruApiReferencePage]] as const) {
  assert.match(source, /globalJsonLd/, `${label} api-reference should include global Organization and WebSite JSON-LD`);
  assert.match(source, /application\/ld\+json/, `${label} api-reference should render JSON-LD`);
  assert.match(source, /Astro\.csp\?\.insertScriptHash/, `${label} api-reference JSON-LD must be allowed by CSP hash`);
}
